version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile  # Your Dockerfile for the Flask app
    ports:
      - "8080:8080"  # Map host port to container port
    depends_on:
      - db  # Depends on the database service
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgresql://username:password@db/dbname  # Replace with your database URI
    command: flask run --host=0.0.0.0 --port=8080

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
